edition = "2021"
use_try_shorthand = true
use_field_init_shorthand = true
imports_granularity = "Crate"
reorder_impl_items = true
format_strings = true
format_code_in_doc_comments = true
condense_wildcard_suffixes = true
group_imports = "StdExternalCrate"
