name: build

on:
  pull_request:
    branches: [main, master, alpha, beta]
  workflow_call:
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # for checkout
  id-token: write # OIDC token for Sigstore signing
  attestations: write # persist build-provenance attestations

jobs:
  linux_nix:
    uses: SpiralP/github-reusable-workflows/.github/workflows/build.yml@01ff23099e2dcfb8772156cfa951f61d30ef6a88 # main

  windows:
    name: Build Windows ${{ matrix.config.arch }}
    runs-on: windows-2025
    strategy:
      fail-fast: false
      matrix:
        config:
          - { arch: x86_64, target: x86_64-pc-windows-msvc }
          - { arch: i686, target: i686-pc-windows-msvc }
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: SpiralP/github-reusable-workflows/.github/actions/build-classicube-plugin@5ce71da308d0133b7401adccbf2a01bec2edacbd # main
        with:
          arch: ${{ matrix.config.arch }}
          target: ${{ matrix.config.target }}

  linux:
    name: Build Linux ${{ matrix.config.arch }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - { arch: x86_64, target: x86_64-unknown-linux-gnu }
          - { arch: aarch64, target: aarch64-unknown-linux-gnu }
          - { arch: i686, target: i686-unknown-linux-gnu }
          - { arch: armhf, target: armv7-unknown-linux-gnueabihf }

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install x86_64 deps
        if: ${{ matrix.config.arch == 'x86_64' }}
        run: |
          sudo apt-get -y update
          sudo apt-get -y install pkg-config libssl-dev libssl3

      - name: Install i686 deps
        if: ${{ matrix.config.arch == 'i686' }}
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get -y update
          sudo apt-get -y install pkg-config:i386 \
            gcc-multilib g++-multilib \
            libssl-dev:i386 \
            libssl3:i386
          echo "PKG_CONFIG_ALLOW_CROSS=1" >> "$GITHUB_ENV"
      - uses: SpiralP/github-reusable-workflows/.github/actions/build-classicube-plugin@5ce71da308d0133b7401adccbf2a01bec2edacbd # main
        with:
          arch: ${{ matrix.config.arch }}
          target: ${{ matrix.config.target }}
          use-cross: ${{ matrix.config.arch == 'aarch64' || matrix.config.arch == 'armhf' }}

  mac:
    name: Build MacOS ${{ matrix.config.arch }}
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        config:
          - { arch: aarch64, target: aarch64-apple-darwin }
          - { arch: x86_64, target: x86_64-apple-darwin }
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: SpiralP/github-reusable-workflows/.github/actions/build-classicube-plugin@5ce71da308d0133b7401adccbf2a01bec2edacbd # main
        with:
          arch: ${{ matrix.config.arch }}
          target: ${{ matrix.config.target }}
