name: Release

on:
  push:
    branches: [master, main]
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false # don't cancel, since the commit this flow pushes will trigger it again

permissions: {} # none, since we use a custom app

jobs:
  release:
    uses: SpiralP/github-reusable-workflows/.github/workflows/release.yml@575cd65e188a9f3afbea756c4651da5b95548e0f # main
    with:
      replace-files: |
        Cargo.lock
        Cargo.toml
    secrets:
      app-id: ${{ secrets.APP_ID }}
      app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
