name: Rust
on: [push]

jobs:
  buildForSomePlatforms:
    name: Build Windows ${{ matrix.config.arch }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { arch: x86_64, bits: 64 }
          - { arch: i686, bits: 32 }

    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: |
          iwr -useb get.scoop.sh | iex
          echo "##[add-path]$HOME\scoop\shims"
          echo "##[add-path]C:\ProgramData\scoop\shims"
          scoop install aria2
          scoop install --arch ${{ matrix.config.bits }}bit llvm
          echo "::set-env name=LIBCLANG_PATH::$HOME\scoop\apps\llvm\current\bin"

      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.config.arch }}-pc-windows-msvc
          toolchain: nightly-${{ matrix.config.arch }}-pc-windows-msvc
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/') != true
        with:
          target: ${{ matrix.config.arch }}-pc-windows-msvc
          command: build

      - name: Test
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/') != true
        with:
          target: ${{ matrix.config.arch }}-pc-windows-msvc
          command: test
          args: -- --nocapture

      - name: Build Release
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          target: ${{ matrix.config.arch }}-pc-windows-msvc
          command: build
          args: --release

      - run: Rename-Item -Path "target\release\classicube_cef_loader_plugin.dll" -NewName "classicube_cef_loader_windows_${{ matrix.config.arch }}.dll"
        if: startsWith(github.ref, 'refs/tags/')

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/classicube_cef_loader_windows_${{ matrix.config.arch }}.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linux:
    name: Build Linux ${{ matrix.config.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { arch: x86_64, bits: 64 }
          # I don't want to figure out the dependencies on 32 bit linux
          # - { arch: i686, bits: 32 }

    steps:
      - uses: actions/checkout@v2

      - name: Install 64 bit deps
        if: matrix.config.bits == 64
        run: |
          sudo apt-get -y update \
            && sudo apt-get -y install clang llvm

      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.config.arch }}-unknown-linux-gnu
          toolchain: nightly-${{ matrix.config.arch }}-unknown-linux-gnu
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/') != true
        with:
          target: ${{ matrix.config.arch }}-unknown-linux-gnu
          command: build

      - name: Test
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/') != true
        with:
          target: ${{ matrix.config.arch }}-unknown-linux-gnu
          command: test
          args: -- --nocapture

      - name: Build Release
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          target: ${{ matrix.config.arch }}-unknown-linux-gnu
          command: build
          args: --release

      - run: mv target/release/libclassicube_cef_loader_plugin.so "classicube_cef_loader_linux_${{ matrix.config.arch }}.so"
        if: startsWith(github.ref, 'refs/tags/')

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: classicube_cef_loader_linux_${{ matrix.config.arch }}.so
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
